/// The Postgres query provider.
///
/// Owns a `package:postgres` [Connection] and
/// exposes the [AsyncQueryProvider] contract
/// that the rest of d_rocket talks to. The
/// wire-protocol client speaks the Postgres v3
/// protocol over TCP; there is no native libpq
/// binding to manage.
///
/// ## Placeholder conversion
///
/// d_rocket's SQL translator (in the SQLite
/// engine) emits `?`-style placeholders. The
/// Postgres wire protocol uses `$1, $2, ...`
/// (positional, dollar-numbered). The provider
/// transparently rewrites `?` to `$N` in
/// `executeAsync` / `selectAsync` so callers can
/// use either form; the wire protocol only ever
/// sees `$N`. The rewrite is `O(n)` in the
/// placeholder count and is the same algorithm
/// every other Postgres Dart ORM uses.
///
/// ## Row format
///
/// `selectAsync` returns `List<Map<String, Object?>>`
/// — one map per row, with the column name as
/// the key and the column value as the value
/// (typed as `Object?` so `int`, `String`,
/// `DateTime`, `List<int>` (BYTEA), and custom
/// `TypeRegistry` types all fit through the
/// same channel). The d_rocket ORM consumes
/// this format via `EntityMeta.fromRow`, which
/// is generated by the codegen and does not
/// care which engine produced the row.
library;

import 'package:d_rocket/d_rocket.dart';
import 'package:postgres/postgres.dart';

/// Wraps a [Connection] from `package:postgres`
/// and exposes the [AsyncQueryProvider] contract.
class PostgresQueryProvider implements AsyncQueryProvider {
  final Connection _conn;
  bool _disposed = false;
  bool _inTransaction = false;

  PostgresQueryProvider._(this._conn);

  /// Opens a connection from a Postgres connection
  /// URL (the [url] parameter) and returns a
  /// ready-to-use [PostgresQueryProvider].
  ///
  /// The URL format is the standard
  /// `postgres://user:pass@host:port/dbname`
  /// (DSN-style), optionally with query
  /// parameters like `?sslmode=require`. The
  /// `package:postgres` `Connection.openFromUrl`
  /// accepts both URL and DSN forms; both are
  /// forwarded unchanged.
  ///
  /// If the URL does not embed a password and
  /// [password] is non-null, [password] is used
  /// as the connection password (the [url] is
  /// re-written to embed the password before
  /// the call to `Connection.openFromUrl`). If
  /// the URL embeds a password, [password] is
  /// ignored.
  static Future<PostgresQueryProvider> openFromUrl({
    required String url,
    String? password,
  }) async {
    final String effectiveUrl =
        (password != null && !_urlHasPassword(url))
            ? _injectPassword(url, password)
            : url;
    return _wrapOpen(Connection.openFromUrl(effectiveUrl));
  }

  /// helper: returns true if the URL's userinfo
  /// already contains a `:` (i.e. the user has
  /// a password embedded). DSN-style URLs use
  /// `host=... port=... user=... password=...`
  /// (no userinfo with `:`); URL-style URLs use
  /// `postgres://user:pass@host/db`. The check
  /// is "contains `://` AND contains a `:`
  /// after the `://` and before the next `@`".
  static bool _urlHasPassword(String url) {
    final int schemeEnd = url.indexOf('://');
    if (schemeEnd < 0) {
      // DSN-style — assume no password in the
      // URL. The caller can still pass a
      // password; we'll inject it into the URL
      // only if the URL has a recognizable
      // form.
      return false;
    }
    final int userInfoStart = schemeEnd + 3;
    final int atSign = url.indexOf('@', userInfoStart);
    if (atSign < 0) return false;
    final String userInfo = url.substring(userInfoStart, atSign);
    return userInfo.contains(':');
  }

  /// helper: injects a password into a URL's
  /// userinfo. If the URL has no userinfo, the
  /// password is added as a query string
  /// parameter (best-effort). The function is
  /// conservative: it modifies the URL only
  /// when the URL is parseable as
  /// `scheme://userinfo@host...`.
  static String _injectPassword(String url, String password) {
    final int schemeEnd = url.indexOf('://');
    if (schemeEnd < 0) return url;
    final int userInfoStart = schemeEnd + 3;
    final int atSign = url.indexOf('@', userInfoStart);
    if (atSign < 0) {
      // No userinfo — append password as a
      // query parameter. The `package:postgres`
      // connection string parser accepts
      // `password=...` in DSN form; for URL
      // form, we use the
      // `postgres://user:pass@host` form and
      // require a username. Best-effort: skip
      // the injection.
      return url;
    }
    final String userInfo = url.substring(userInfoStart, atSign);
    if (userInfo.contains(':')) {
      // Already has a password.
      return url;
    }
    final String rest = url.substring(atSign);
    return '${url.substring(0, userInfoStart)}$userInfo:$password$rest';
  }

  /// Opens a connection from individual
  /// parameters. Use this when you don't want to
  /// pass the full URL (e.g. when the password
  /// is read from a vault at runtime).
  static Future<PostgresQueryProvider> open({
    required String host,
    int port = 5432,
    required String database,
    required String username,
    String? password,
    SslMode sslMode = SslMode.disable,
  }) async {
    return _wrapOpen(
      Connection.open(
        Endpoint(
          host: host,
          port: port,
          database: database,
          username: username,
          password: password,
        ),
        settings: ConnectionSettings(sslMode: sslMode),
      ),
    );
  }

  /// Wraps an existing [Connection] instance.
  /// Use this when the caller has already opened
  /// the connection (e.g. from a connection
  /// pool) and wants to keep ownership of the
  /// lifecycle.
  factory PostgresQueryProvider.fromConnection(Connection conn) =>
      PostgresQueryProvider._(conn);

  static Future<PostgresQueryProvider> _wrapOpen(
    Future<Connection> pending,
  ) async {
    try {
      final Connection conn = await pending;
      return PostgresQueryProvider._(conn);
    } on DatabaseException {
      rethrow;
    } on PgException catch (e) {
      throw DatabaseException(
        'Failed to open Postgres connection: ${e.toString()}',
        cause: e,
      );
    } catch (e) {
      throw DatabaseException(
        'Failed to open Postgres connection: ${e.toString()}',
        cause: e,
      );
    }
  }

  /// helper: same pattern as the SQLite
  /// provider's `_wrap` / `_wrapAsync` — wraps
  /// sync / async errors in [DatabaseException]
  /// so the d_rocket ORM can catch a single
  /// exception type.
  Future<T> _wrapAsync<T>(Future<T> Function() op) async {
    try {
      return await op();
    } on DatabaseException {
      rethrow;
    } on PgException catch (e) {
      // `PgException` exposes the message and
      // (for `ServerException`) the SQL position
      // and error code, but not the original SQL
      // string. The d_rocket `DatabaseException`
      // has a `sql` field for the original SQL;
      // we pass the `message` and let the caller
      // know the source is a `PgException` via
      // the `cause` field.
      final String detail = e is ServerException && e.code != null
          ? '${e.code}: ${e.message}'
          : e.message;
      throw DatabaseException(
        detail,
        cause: e,
      );
    } catch (e) {
      throw DatabaseException(e.toString(), cause: e);
    }
  }

  @override
  bool get isOpen => !_disposed && _conn.isOpen;

  @override
  Future<List<Object?>> selectAsync(String sql, [List<Object?>? binds]) {
    return _wrapAsync(() async {
      final String rewritten = _rewritePlaceholders(sql);
      final Result result = await _conn.execute(
        rewritten,
        parameters: binds,
        ignoreRows: false,
      );
      return result
          .map((ResultRow row) => row.toColumnMap())
          .toList(growable: false);
    });
  }

  @override
  Future<void> executeAsync(String sql, [List<Object?>? binds]) {
    return _wrapAsync(() async {
      final String rewritten = _rewritePlaceholders(sql);
      await _conn.execute(
        rewritten,
        parameters: binds,
        ignoreRows: true,
      );
    });
  }

  @override
  Future<int> lastInsertRowIdAsync() async {
    // Postgres does not have a per-connection
    // "last insert id" like SQLite's
    // `lastInsertRowId`. The standard way to
    // get the inserted id is the `INSERT ...
    // RETURNING <pk>` clause. We throw a clear
    // error so the dev knows to switch to
    // RETURNING.
    throw DatabaseException(
      'PostgresQueryProvider.lastInsertRowIdAsync() is not '
      'supported. Use the SQL `INSERT ... RETURNING <pk>` '
      'clause and read the returned id from the result '
      'rows. The d_rocket codegen emits RETURNING for '
      '@Table classes with a single-column integer primary '
      'key (SERIAL / BIGSERIAL).',
    );
  }

  @override
  Future<void> beginTransactionAsync() async {
    if (_inTransaction) {
      throw DatabaseException(
        'A transaction is already active. Nested transactions '
        'are not supported in the MVP. If you need savepoints, '
        'use SAVEPOINT / RELEASE / ROLLBACK TO directly.',
      );
    }
    return _wrapAsync(() async {
      await _conn.execute('BEGIN', ignoreRows: true);
      _inTransaction = true;
    });
  }

  @override
  Future<void> commitAsync() async {
    if (!_inTransaction) return;
    return _wrapAsync(() async {
      await _conn.execute('COMMIT', ignoreRows: true);
      _inTransaction = false;
    });
  }

  @override
  Future<void> rollbackAsync() async {
    if (!_inTransaction) return;
    return _wrapAsync(() async {
      await _conn.execute('ROLLBACK', ignoreRows: true);
      _inTransaction = false;
    });
  }

  @override
  Future<void> disposeAsync() async {
    _disposed = true;
    if (_inTransaction) {
      // Best-effort rollback if dispose is
      // called mid-transaction. The connection
      // close() will discard any open
      // transaction anyway, but we try to
      // emit the ROLLBACK so the server logs
      // show a clean shutdown.
      try {
        await _conn.execute('ROLLBACK', ignoreRows: true);
      } on Object {
        // ignore — we're disposing
      }
      _inTransaction = false;
    }
    await _conn.close();
  }

  /// helper: rewrites `?` placeholders to
  /// `$1, $2, ...` so the SQL is valid on the
  /// Postgres wire protocol. The rewrite is
  /// naive but correct: it counts the `?` in
  /// order and emits `$N` for each. It does
  /// not try to detect `?` inside string
  /// literals or comments — if the dev has a
  /// `?` inside a literal, the rewrite will
  /// produce invalid SQL. The recommended
  /// approach is to use `$N` placeholders
  /// directly when authoring Postgres SQL
  /// by hand; the `?` form is for code that
  /// was originally SQLite-flavored.
  String _rewritePlaceholders(String sql) {
    if (!sql.contains('?')) return sql;
    final StringBuffer buf = StringBuffer();
    int n = 0;
    for (int i = 0; i < sql.length; i++) {
      final int code = sql.codeUnitAt(i);
      if (code == 0x3F /* ? */) {
        n++;
        buf.write('\$');
        buf.write(n);
      } else {
        buf.writeCharCode(code);
      }
    }
    return buf.toString();
  }

  /// The underlying [Connection]. Exposed for
  /// advanced use cases (e.g. running a
  /// statement that returns a `Result` directly
  /// without the AsyncQueryProvider
  /// wrap-and-unwrap).
  Connection get connection => _conn;
}
